<h2>Éditer le pack</h2>

<form action="" method="POST" enctype="multipart/form-data">
    <div class="form">
        <div>
            <div class="form-input">
                <label for="pack-title">Titre</label>
                <input type="text" id="pack-title" name="pack-title" value="<?= $pack->getTitle() ?>">
                <?php if (isset($pack_errors['title'])) : ?>
                    <p class="error"><?= $pack_errors['title'] ?></p>
                <?php endif ?>
            </div>
            <div class="form-input">
                <label for="price">Prix</label>
                <input type="number" id="price" name="price" value="<?= $pack->getPrice() ?>">
                <?php if (isset($pack_errors['price'])) : ?>
                    <p class="error"><?= $pack_errors['price'] ?></p>
                <?php endif ?>
            </div>
        </div>
        <div class="form-input">
            <label for="image">Image</label>
            <img src="<?= asset('images/' . $pack->getImage()) ?>" alt="<?= $pack->getImage() ?>">
            <input type="file" id="image" name="image">
            <?php if (isset($pack_errors['image'])) : ?>
                <p class="error"><?= $pack_errors['image'] ?></p>
            <?php endif ?>
        </div>
        <div class="form-input">
            <label for="description">Description</label>
            <textarea type="" id="description" name="description"><?= strip_tags($pack->getDescription()) ?></textarea>
            <?php if (isset($pack_errors['description'])) : ?>
                <p class="error"><?= $pack_errors['description'] ?></p>
            <?php endif ?>
        </div>
    </div>
    <input type="submit" name="edit-pack" value="Modifier le pack">
</form>
<br>

<?php if (!empty($videos)) { ?>

    <form action="" method="POST" class="form-table">
        <table border="1">
            <thead>
                <th colspan="5">Les vidéos du pack</th>
            </thead>
            <tr>
                <th>Titre</th>
                <th>Fichier</th>
                <th>Ordre</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
            <?php foreach ($videos as $video): ?>
                <tr>
                    <td><input type="text" name="video-title-<?= $video->getId() ?>" value="<?= $video->getTitle() ?>"></td>
                    <td>
                        <p style="margin:0"><?= $video->getFilename() ?></p>
                        <input type="hidden" name="actual-filename-<?= $video->getId() ?>" value="<?= $video->getFilename() ?>">
                        <input type="file" name="video-filename-<?= $video->getId() ?>">
                    </td>
                    <td><input type="number" name="rank-order-<?= $video->getId() ?>" value="<?= $video->getRankOrder() ?>"></td>
                    <td><input type="submit" name="edit-<?= $video->getId() ?>" value="Modifier"></td>
                    <td><input type="submit" name="delete-<?= $video->getId() ?>" value="Supprimer"></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </form>

<?php } else { ?>

    <div class="frame">
        <p>Aucune vidéo pour l'instant</p>
    </div>

<?php } ?>
<br>

<form action="" method="POST" enctype="multipart/form-data">
    <legend>Ajouter une vidéo</legend>
    <div class="form">
        <div class="form-input">
            <label for="video-title">Titre de la vidéo</label>
            <input type="text" id="video-title" name="video-title">
            <?php if (isset($video_errors['title'])) : ?>
                <p class="error"><?= $video_errors['title'] ?></p>
            <?php endif ?>
        </div>
        <div class="form-input">    
            <label for="video-filename">Fichier vidéo</label>
            <input type="file" id="video-filename" name="video-filename">
            <?php if (isset($video_errors['filename'])) : ?>
                <p class="error"><?= $video_errors['filename'] ?></p>
            <?php endif ?>
        </div>
        <div class="form-input">    
            <label for="rank-order">Ordre de classement</label>
            <input type="number" id="rank-order" name="rank-order">
            <?php if (isset($video_errors['rank_order'])) : ?>
                <p class="error"><?= $video_errors['rank_order'] ?></p>
            <?php endif ?>
        </div>
    </div>
    <input type="submit" name="add-video" value="Ajouter une vidéo">
</form>
<br>

<div class="frame">
    <legend>Supprimer le pack</legend>
    <input type="button" value="Supprimer" class="delete">
</div>
<br>

<div class="pop-up-background">
</div>

<form class="pop-up" method="POST">
    <p>Êtes-vous sûr de vouloir supprimer le pack <b><?= $pack->getTitle() ?></b> ?</p>
    <p>Tous les utilisateurs ayant acheté ce pack en perdront l'accès !</p>
    <p class="warning"><b>Cette action est irréversible !</b></p>
    <input type="submit" name="delete-pack" value="Supprimer le pack">
    <input type="button" value="Annuler" class="cancel">
</form>

<script src="<?= asset('js/deletePopUp.js') ?>"></script>