<h2>Éditer l'utilisateur</h2>

<form action="" method="POST">
    <div class="form-input">    
        <label for="lastname">Nom</label>
        <input type="text" id="lastname" name="lastname" value="<?= $user['lastname'] ?>">
        <?php if(isset($errors['lastname'])) : ?>
            <p class="error"><?= $errors['lastname'] ?></p>
        <?php endif ?>
    </div>
    <div class="form-input">
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" name="firstname" value="<?= $user['firstname'] ?>">
        <?php if(isset($errors['firstname'])) : ?>
            <p class="error"><?= $errors['firstname'] ?></p>
        <?php endif ?>
    </div>
    <div class="form-input"> 
        <label for="email">Email</label>
        <input type="email" id="email" name="email" value="<?= $user['email'] ?>">
        <?php if(isset($errors['email'])) : ?>
            <p class="error"><?= $errors['email'] ?></p>
        <?php endif ?>
    </div>
    <p>Inscris le <?= $user['createdAt'] ?></p>
    <input type="submit" name="edit-user" value="Modifier l'utilisateur">
</form>
<br>

<?php if(!empty($userPacks)) { ?>
<form action="" method="POST" class="form-table">
    <table border="1">
        <thead>
            <th colspan="5">Souscription(s) de l'utilisateurs</th>
        </thead>
        <?php foreach($userPacks as $pack): ?>
            <tr>
                <td><?= $pack['title'] ?></td>
                <td>Acheté le<br><?= $pack['purchased_on'] ?></td>
                <td><input type="submit" name="delete-<?= $pack['pack_id'] ?>" value="Retirer le pack"></td>
            </tr>
        <?php endforeach; ?>
    </table>
</form>
<?php } else { ?>
    <div class="frame">
        <p>L'utilisateur n'a souscris à aucun pack pour l'instant</p>
    </div>
<?php } ?>
<br>

<form action="" method="POST">
    <legend>Ajouter un pack à l'utilisateur</legend>

    <select name="pack-selected">
        <?php foreach($packSelection as $pack): ?>
            <?php if(!in_array($pack['id'], $userPacksId)) { ?>
                <option value="<?= $pack['id'] ?>"><?= $pack['title'] ?></option>
            <?php } ?>
        <?php endforeach; ?>
    </select>

    <input type="submit" name="add-pack" value="Ajouter le pack">
</form>
<br>

<?php if($user['role'] != 'admin') : ?>

    <div class="frame">
        <legend>Supprimer l'utilisateur</legend>
        <input type="button" value="Supprimer" class="delete">
    </div>
    <br>

    <div class="pop-up-background">
    </div>

    <form class="pop-up" method="POST">
        <p>Êtes-vous sûr de vouloir supprimer l'utilisateur <b><?= $user['lastname'] .' '. $user['firstname'] .'</b> ('. $user['email'] .')' ?> ?</p>
        <p>Il perdra l'accès à tous ses packs !</p>
        <p class="warning"><b>Cette action est irréversible !</b></p>
        <input type="submit" name="delete-user" value="Supprimer l'utilisateur">
        <input type="button" value="Annuler" class="cancel">
    </form>

<?php endif ?>

<script src="<?= asset('js/deletePopUp.js') ?>"></script>