<br>
<?php foreach ($sections as $section) : ?>

    <form action="" method="POST">
        <div class="form-input">
            <label for="title-<?= $section['id'] ?>">Titre de la section</label>
            <input type="text" id="title-<?= $section['id'] ?>" name="title-<?= $section['id'] ?>" value="<?= $section['title'] ?>">
        </div>
        <div class="form-input">
            <label for="content-<?= $section['id'] ?>">Contenu de la section</label>
            <textarea name="content-<?= $section['id'] ?>" id="content-<?= $section['id'] ?>" cols="30" rows="10"><?= strip_tags($section['content']) ?></textarea>
        </div>
        <input type="submit" name="update-section-<?= $section['id'] ?>" value="Modifer">
    </form>
    <br>
    
<?php endforeach ?>