<!-- <form action="" method="POST">
    <legend>Envoyer une carte cadeau</legend>
    <select name="pack" id="pack">
        <?php foreach($packs as $pack): ?>
            <option value="<?= $pack['id'] ?>"><?= $pack['title'] ?></option>
        <?php endforeach; ?>
    </select>
    <input type="email" id="gift-card" name="gift-card" placeholder="Email du destinataire">
    <input type="submit" name="submit-gift" value="Envoyer">
</form>
<br> -->

<form action="" method="POST">
    <legend>Ajouter un Pack de vidéo(s)</legend>
    <div class="form-input">
        <label for="title">Titre</label>
        <input type="text" id="title" name="title">
        <?php if(isset($errors['title'])) { ?>
            <p class="error"><?= $errors['title'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="price">Prix</label>
        <input type="number" id="price" name="price">
        <?php if(isset($errors['price'])) { ?>
            <p class="error"><?= $errors['price'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="image">Image</label>
        <input type="file" id="image" name="image">
        <?php if(isset($errors['image'])) { ?>
            <p class="error"><?= $errors['image'] ?></p>
        <?php } ?>
    </div>
    <input type="submit" name="create-pack" value="Créer un pack">
</form>
<br>

<table border="1">
    <thead>
        <th colspan="4">Liste des packs</th>
    </thead>
    <tr>
        <th>Titre</th>
        <th>Prix</th>
        <th>Nb Vidéo(s)</th>
        <th>Modifier</th>
    </tr>
    <?php foreach($packs as $pack): ?>
        <tr>
            <td><?= $pack['title'] ?></td>
            <td><?= $pack['price'] ?> €</td>
            <td><?= count($videoModel->getVideosByPack($pack['id'])) ?></td>
            <td><a href="<?= constructUrl('/edit-pack', ['id' => $pack['id']]) ?>">Modifier</a></td>
        </tr>
    <?php endforeach; ?>
</table>
<br>

<table border="1">
    <thead>
        <th colspan="6">Liste des utilisateurs</th>
    </thead>
    <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>Email</th>
        <th>Date d'inscription</th>
        <th>Souscription</th>
        <th>Modifier</th>
    </tr>
    <?php foreach($users as $user): ?>
        <tr>
            <td><?= $user->getLastname() ?></td>
            <td><?= $user->getFirstname() ?></td>
            <td><?= $user->getEmail() ?></td>
            <td><?= $user->getFormattedCreatedAt() ?></td>
            <td><?php $userPacks = $userModel->getUserPacks($user->getId()) ?>
                <?php if($userPacks): ?>
                    <?php foreach($userPacks as $pack): ?>
                        <?= $pack['title'] ?><br>
                    <?php endforeach; ?>
                <?php endif; ?>
            </td>
            <td><a href="<?= constructUrl('/edit-user', ['id' => $user->getId()]) ?>">Modifier</a></td>
        </tr>
    <?php endforeach; ?>
</table>