<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Isa Danse</title>
    <link rel="stylesheet" href="<?=asset('css/style.css')?>">
    <link rel="stylesheet" href="<?=asset('css/' . $template . '.css')?>">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Niconne&display=swap" rel="stylesheet">

    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
</head>

<body>
    <head>
        <nav>
            <div class="nav-bar">
                <a href="<?= constructUrl('home') ?>">Accueil</a>
                <?php if(!isset($_SESSION['user'])) { ?>
                    <a href="<?= constructUrl('login') ?>">Connexion</a>
                    <a href="<?= constructUrl('register') ?>">Inscription</a>
                <?php } elseif(isset($_SESSION['user'])) { ?>
                    <?php if($_SESSION['user']['role'] == 'admin'): ?>
                        <a href="<?= constructUrl('admin') ?>">Administrateur</a>
                    <?php endif; ?>
                    <a href="<?= constructUrl('member') ?>">Espace membre</a>
                    <a href="<?= constructUrl('profile') ?>">Mon profil</a>
                    <a href="<?= constructUrl('logout') ?>">Déconnexion</a>
                <?php } ?>
                <a href="<?= constructUrl('contact') ?>">Contact</a>
            </div>
            <div class="nav-burger">
                <div class="menu-burger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>
            <div class="hidden-menu">
                <a href="<?= constructUrl('home') ?>">Accueil</a>
                <?php if(!isset($_SESSION['user'])) { ?>
                    <a href="<?= constructUrl('login') ?>">Connexion</a>
                    <a href="<?= constructUrl('register') ?>">Inscription</a>
                <?php } elseif(isset($_SESSION['user'])) { ?>
                    <?php if($_SESSION['user']['role'] == 'admin'): ?>
                        <a href="<?= constructUrl('admin') ?>">Administrateur</a>
                    <?php endif; ?>
                    <a href="<?= constructUrl('member') ?>">Espace membre</a>
                    <a href="<?= constructUrl('profile') ?>">Mon profil</a>
                    <a href="<?= constructUrl('logout') ?>">Déconnexion</a>
                <?php } ?>
                <a href="<?= constructUrl('contact') ?>">Contact</a>
                <img class="close-menu" src="<?= asset('images/close.png') ?>" alt="Fermer">
            </div>
        </nav>
    </head>

    <main>
        <?php include $template . '.phtml'; ?>
    </main>

    <footer>
        <p>© Isabelle Manzanares. Tous droits réservés.</p>
        <div class="social-media">
            <a href="https://www.facebook.com/hola.isabelle"><img src="<?=asset('/images/facebook.png')?>" alt=""></a>
            <a href="https://www.youtube.com/channel/UC-5FkbLYr11nVC65PpWdt1A"><img src="<?=asset('/images/youtube.png')?>" alt=""></a>
            <a href="https://www.instagram.com/isabellemanzanares"><img src="<?=asset('/images/instagram.png')?>" alt=""></a>
        </div>
        <p><a href="https://www.isabelle-manzanares.com">https://www.isabelle-manzanares.com</a></p>
    </footer>

    <script>

        const menuBurger = document.querySelector('.menu-burger');
        const hiddenMenu = document.querySelector('.hidden-menu');
        const closeMenu = document.querySelector('.close-menu');

        const main = document.querySelector('main');

        menuBurger.addEventListener('click', () => {
            hiddenMenu.style.display = 'flex';
        })

        closeMenu.addEventListener('click', () => {
            hiddenMenu.style.display = 'none';
        })

        main.addEventListener('click', () => {
            hiddenMenu.style.display = 'none';
        })

    </script>
</body>
</html>