<h2>Contact</h2>

<form action="<?= constructUrl('contact') ?>" method="POST" id="contact-form">
    <div class="form-input">
        <label for="email">Email</label>
        <input type="email" id="email" name="email">
    </div>
    <div class="form-input">
        <label for="subject">Sujet</label>
        <input type="text" id="subject" name="subject">
    </div>
    <div class="form-input">
        <label for="message">Message</label>
        <textarea name="message" id="message"></textarea>
    </div>
    <input type="submit" value="Envoyer">
</form>
<br>

<script src="<?= asset('js/contact.js') ?>"></script>