<h2>Éditer l'utilisateur</h2>

<form action="" method="POST">
    <div class="form-input">    
        <label for="lastname">Nom</label>
        <input type="text" id="lastname" name="lastname" value="<?= $user['lastname'] ?>">
        <?php if(isset($errors['lastname'])) : ?>
            <p class="error"><?= $errors['lastname'] ?></p>
        <?php endif ?>
    </div>
    <div class="form-input">
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" name="firstname" value="<?= $user['firstname'] ?>">
        <?php if(isset($errors['firstname'])) : ?>
            <p class="error"><?= $errors['firstname'] ?></p>
        <?php endif ?>
    </div>
    <div class="form-input"> 
        <label for="email">Email</label>
        <input type="email" id="email" name="email" value="<?= $user['email'] ?>">
        <?php if(isset($errors['email'])) : ?>
            <p class="error"><?= $errors['email'] ?></p>
        <?php endif ?>
    </div>
    <input type="submit" name="edit-user" value="Modifier l'utilisateur">
</form>
<br>

<form action="" method="POST">
    <legend>Souscription(s) de l'utilisateur</legend>

    <?php if(!empty($userPacks)) {?>
        <?php foreach($userPacks as $pack) { ?>
            <p style="margin:0"><?= $pack['title']. ' ' ?><input style="margin-bottom:0" type="submit" name="delete-<?= $pack['pack_id'] ?>" value="Retirer le pack"></p>
        <?php } ?>
    <?php } else { ?>
        <p>Aucun pack pour l'instant</p>
    <?php } ?>

    <select name="pack-selected">
        <?php foreach($packs as $pack): ?>
            <option value="<?= $pack['id'] ?>"><?= $pack['title'] ?></option>
        <?php endforeach; ?>
    </select>

    <input type="submit" name="add-pack" value="Ajouter le pack">
</form>
<br>

<div class="frame">
    <legend>Supprimer l'utilisateur</legend>
    <a href="<?= constructUrl('/delete-user', ['id' => $_GET['id']])?>"><input type="button" value="Supprimer"></a>
</div>
<br>