<h2>Mot de passe oublié</h2>

<?php if ($section == 'code') { ?>

    <form action=""method="POST">
        <legend>Un code de récupération vous a été envoyé par email</legend>
        <div class="form-input">
            <label for="verif-code">Entrez le code de récupération</label>
            <input type="text" id="verif-code" name="verif-code">
            <?php if (isset($errors['code'])) { ?>
                <p class="error"><?= $errors['code'] ?></p>
            <?php } ?>
        </div>
        <input type="submit" name="verif-submit" value="Valider">
    </form>

<?php } elseif ($section == 'changepassword') { ?>

    <form action=""method="POST">
        <legend>Choisissez votre nouveau mot de passe</legend>
        <div class="form-input">
            <label for="new-password">Nouveau mot de passe</label>
            <input type="password" id="new-password" name="new-password">
            <?php if (isset($errors['new_password'])) { ?>
                <p class="error"><?= $errors['new_password'] ?></p>
            <?php } ?>
        </div>
        <div class="form-input">
            <label for="new-password2">Confirmer le mot de passe</label>
            <input type="password" id="new-password2" name="new-password2">
            <?php if (isset($errors['new_password2'])) { ?>
                <p class="error"><?= $errors['new_password2'] ?></p>
            <?php } ?>
        </div>
        <input type="submit" name="change-submit" value="Valider">
    </form>

<?php } else { ?>

    <form action=""method="POST">
        <legend>Vous avez oublié votre mot de passe ?</legend>
        <div class="form-input">
            <label for="email">Entrez votre adresse email</label>
            <input type="text" id="email" name="email">
            <?php if (isset($errors['email'])) { ?>
                <p class="error"><?= $errors['email'] ?></p>
            <?php } ?>
        </div>
        <input type="submit" name="recup-submit" value="Valider">
    </form>
    
<?php } ?>

<?php if (isset($confirmation) && $confirmation == false): ?>
    <div class="confirmation">
        <p>Vous devez valider le code de récupération qui vous a été envoyé par email</p>
        <a href="<?= constructUrl('forgot-password', ['section' => 'code']) ?>">Cliquez ici</a>
    </div>
<?php endif; ?>