<?php if($section == 'code') { ?>
<form action=""method="POST">
    <legend>Un code de vérification vous a été envoyé par email</legend>
    <label for="verif-code">Entrez le code de vérification</label><br>
    <input type="text" id="verif-code" name="verif-code">
    <br>
    <input type="submit" name="verif-submit" value="Valider">
</form>

<?php } elseif($section == 'changepassword') { ?>
<form action=""method="POST">
    <legend>Choisissez votre nouveau mot de passe</legend>
    <label for="new-password">Nouveau mot de passe</label><br>
    <input type="password" id="new-password" name="new-password">
    <br>
    <label for="new-password2">Confirmer le mot de passe</label><br>
    <input type="password" id="new-password2" name="new-password2">
    <br>
    <input type="submit" name="change-submit" value="Valider">
</form>

<?php } else { ?>
<form action=""method="POST">
    <legend>Mot de passe oublié ?</legend>
    <label for="email">Entrez votre adresse email</label><br>
    <input type="email" id="email" name="email">
    <br>
    <input type="submit" name="recup-submit" value="Valider">
</form>
<?php } ?>

<?php if(isset($errors)): ?>
    <p class="error"><?= $errors ?></p>
<?php endif; ?>