<div class="top-page-home">
    <video autoplay="autoplay" muted="muted" loop src="<?= asset('videos/teaser-complet.mp4') ?>"></video>
</div>

<h2>COURS EN LIGNE</h2>
<p class="h2-subtitle">pour progresser de chez vous, à votre rythme</p>

<div class="presentation-text">
    <p><?= $sections[0]['content'] ?></p>
</div>

<h3>THÈMES ABORDÉS</h3>
<div class="packs-presentation">
    <div class="pack-bachata">
        <img class="pack-image" src="<?= asset('images/pack-bachata.png') ?>" alt="">
        <p><u>COURS TECHNIQUES</u><br>
        Bassin (variantes Bachata)<br>
        Vagues<br>
        Mobilité buste/tête<br>
        Tours<br>
        Gestuelle des bras<br>
        <br>
        <u>CHORÉGRAPHIE</u><br>
        Chorégraphie Bachata - débutante<br>
        Chorégraphie Bachata - intermédiaire</p>
    </div>
    <div class="pack-salsa">
        <img class="pack-image" src="<?= asset('images/pack-salsa.png') ?>" alt="">
        <p><u>COURS TECHNIQUES</u><br>
        Appuis<br>
        Bassin (variantes Salsa)<br>
        Buste<br>
        Epaules<br>
        Gestuelle des bras<br>
        <br>
        <u>CHORÉGRAPHIE</u><br>
        Chorégraphie Salsa - débutante<br>
        Chorégraphie Salsa - intermédiaire</p>
    </div>
</div>

<h3>APERÇU</h3>
<div class="video-clips">
    <div>
        <p>Extrait choré Bachata</p>
        <video src="<?= asset('videos/extrait-chore-bachata.mp4') ?>" controls poster="<?= asset('images/miniature-chore-bachata.png') ?>"></video>
    </div>
    <div>
        <p>Extrait choré Salsa</p>
        <video src="<?= asset('videos/extrait-chore-salsa.mp4') ?>" controls poster="<?= asset('images/miniature-chore-salsa.png') ?>"></video>
    </div>
    <div>
        <p>Extrait cours technique</p>
        <video src="<?= asset('videos/extrait-cours.mp4') ?>" controls poster="<?= asset('images/miniature-cours.png') ?>"></video>
    </div>
</div>

<img src="<?= asset('images/responsive.png') ?>" alt="" width="200px">
<p class="accessibility">Accessible sur ordinateur, tablette et mobile</p>

<h3 id="packs">ACCÈS AUX PACKS</h3>
<div class="buy-packs">
    <?php foreach($packs as $pack) { ?>
        <div class="pack-to-buy">
            <h4><?= $pack['title'] ?></h4>
            <p class="price"><?= $pack['price'] ?> €</p>
            <p class="buy-description"><?= $pack['description'] ?>
            <p class="select-pack"><a href="<?= constructUrl('purchase', ['id' => $pack['id']]) ?>">Sélectionner</a></p>
        </div>
    <?php } ?>
</div>

<div id="present">
    <img src="<?= asset('images/gift.png') ?>" alt="" width="75px">
    <p class="present">Possibilité d'offrir un pack à un proche, cliquez <a href="<?= constructUrl('present') ?>">ICI</a></p>
</div>

<h3><?= $sections[1]['title'] ?></h3>
<div class="details-text">
    <p><?= $sections[1]['content'] ?></p>
</div>