<?php if(isset($new_user)): ?>
    <p style="color:green"><?= $new_user ?></p>
<?php endif; ?>

<form action="" method="POST">
    <legend>Connexion</legend>
    <div class="form-input">
        <label for="email-login">Email</label>
        <input type="text" id="email-login" name="email-login" value="<?php if(isset($email)) { echo $email; } ?>">
        <?php if(isset($errors['email_login'])) { ?>
            <p class="error"><?= $errors['email_login'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="password-login">Mot de passe</label>
        <input type="password" id="password-login" name="password-login">
        <?php if(isset($errors['password_login'])) { ?>
            <p class="error"><?= $errors['password_login'] ?></p>
        <?php } ?>
    </div>
    <input type="submit" name="login-submit" value="Se connecter">
    <p>Pas encore inscris ? <a href="<?= constructUrl('/register') ?>">S'inscrire</a></p>
    <p><a href="<?= constructUrl('/forgot-password') ?>">Mot de passe oublié ?</a></p>
</form>