<div class="login-page">

<?php if(isset($new_user)): ?>
    <p style="color:green"><?= $new_user ?></p>
<?php endif; ?>

<form action="" method="POST" class="login-form" <?php if ($_SESSION['show_register']) { echo 'style="display:none"'; } ?>>
    <legend>Connexion</legend>
    <div class="form-input">
        <label for="email">Email</label>
        <input type="text" id="email" name="email-login" value="<?php if(isset($email_login)) { echo $email_login; } ?>">
        <?php if(isset($errors['email_login'])) { ?>
            <p class="error"><?= $errors['email_login'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password-login">
        <?php if(isset($errors['password_login'])) { ?>
            <p class="error"><?= $errors['password_login'] ?></p>
        <?php } ?>
    </div>
    <input type="submit" name="login-submit" value="Se connecter">
    <p>Pas encore inscris ? <a href="#" class="register">S'inscrire</a></p>
    <p><a href="<?=constructUrl('/forgot-password')?>">Mot de passe oublié ?</a></p>
</form>

<form action="" method="POST" class="register-form" <?php if ($_SESSION['show_register']) { echo 'style="display:block"'; } ?>>
    <legend>Inscription</legend>
    <div class="form-input">
        <label for="lastname">Nom</label>
        <input type="text" id="lastname" name="lastname" value="<?php if(isset($lastname)) { echo $lastname; } ?>">
        <?php if(isset($errors['lastname'])) { ?>
            <p class="error"><?= $errors['lastname'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="firstname">Prénom</label>
        <input type="text" id="firstname" name="firstname" value="<?php if(isset($firstname)) { echo $firstname; } ?>">
        <?php if(isset($errors['firstname'])) { ?>
            <p class="error"><?= $errors['firstname'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="email">Email</label>
        <input type="email" id="email" name="email" value="<?php if(isset($email)) { echo $email; } ?>">
        <?php if(isset($errors['email'])) { ?>
            <p class="error"><?= $errors['email'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="password">Mot de passe</label>
        <input type="password" id="password" name="password">
        <?php if(isset($errors['password'])) { ?>
            <p class="error"><?= $errors['password'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <label for="password">Confirmer le mot de passe</label>
        <input type="password" id="password2" name="password2">
        <?php if(isset($errors['password2'])) { ?>
            <p class="error"><?= $errors['password2'] ?></p>
        <?php } ?>
    </div>
    <input type="submit" name="register-submit" value="S'inscrire">
    <p>Déjà inscris ? <a href="#" class="login">Se connecter</a></p>
</form>

</div>

<script>

const registerForm = document.querySelector('.register-form');
const loginForm = document.querySelector('.login-form');
const error = document.querySelector('.error');

document.querySelector('.register').addEventListener('click', () => {
    registerForm.style.display = "block";
    loginForm.style.display = "none";
})

document.querySelector('.login').addEventListener('click', () => {
    registerForm.style.display = "none";
    loginForm.style.display = "block";
})

</script>