<?php if (!empty($userPacks)) { ?>

    <?php foreach ($userPacks as $userPack) { ?>    
        <div class="pack">
            <a href="<?=constructUrl('pack', ['id' => $userPack->getPack()->getId()])?>">
                <img class="pack-image" src="<?=asset('images/' . $userPack->getPack()->getImage())?>" alt="<?= $userPack->getPack()->getTitle() ?>">
            </a>
        </div>
    <?php } ?>

<?php } else { ?>

    <div class="text">
        <p>Vous n'avez souscris à aucun pack pour le moment</p>
        <p><a href="<?= constructUrl('home') . '#packs' ?>">Acheter un pack</a></p>
    </div>

<?php } ?>