<h2><?= $pack->getTitle() ?></h2>

<?php if(!empty($videos)) { ?>

    <div class="links">
        <?php foreach($videos as $video) { ?>
            <a href="#<?= $video['id'] ?>"><?= $video['title'] ?></a>
        <?php } ?>
    </div>

    <?php foreach($videos as $video) { ?>
        <div class="video" id="<?= $video['id'] ?>">
            <p><?= $video['title'] ?></p>   
            <video controls src="<?= asset('videos/' . $video['filename']) ?>"></video>
        </div>
    <?php } ?>

<?php } else { ?>
    <p>Ce pack ne contient pas de vidéo</p>
<?php } ?>