<h2><?= $pack->getTitle() ?></h2>

<?php if (!empty($videos)) { ?>

    <div class="links">
        <?php foreach ($videos as $video) { ?>
            <a href="#<?= $video->getId() ?>"><?= $video->getTitle() ?></a>
        <?php } ?>
    </div>

    <?php foreach ($videos as $video) { ?>
        <div class="video" id="<?= $video->getId() ?>">
            <p><?= $video->getTitle() ?></p>   
            <video controls src="<?= asset('videos/' . $video->getFilename()) ?>"></video>
        </div>
    <?php } ?>

<?php } else { ?>
    <p>Ce pack ne contient pas de vidéo</p>
<?php } ?>