<h2>Mon profil</h2>

<div class="profile">
    <p><u>Nom :</u><br><?= $_SESSION['user']['lastname'].' '.$_SESSION['user']['firstname'] ?></p>
    <p><u>Email :</u><br><?= $_SESSION['user']['email'] ?></p>
    <p><u>Souscription(s) :</u><br>
    <?php if(isset($userPacks) AND !empty($userPacks)) {
        foreach($userPacks as $pack) {
            echo $pack['title'].'<br>';
        }
    } else {
        echo "Vous n'avez souscris à aucun pack pour le moment";
    } ?>
    </p>
</div>
<br>

<?php if(isset($password_changed)): ?>
    <p class="success"><?= $password_changed ?></p>
<?php endif; ?>

<form action="" method="POST">
    <legend>Modifier mon mot de passe</legend>
    <div class="form-input">
        <input type="password" name="password" placeholder="Mot de passe actuel">
        <?php if(isset($errors['password'])) { ?>
            <p class="error"><?= $errors['password'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <input type="password" name="new-password" placeholder="Nouveau mot de passe">
        <?php if(isset($errors['new_password'])) { ?>
            <p class="error"><?= $errors['new_password'] ?></p>
        <?php } ?>
    </div>
    <div class="form-input">
        <input type="password" name="new-password2" placeholder="Confirmer le mot de passe">
        <?php if(isset($errors['new_password2'])) { ?>
            <p class="error"><?= $errors['new_password2'] ?></p>
        <?php } ?>
    </div>
    <input type="submit" name="password-submit" value="Modifier">
</form>
<br>

<?php if($_SESSION['user']['role'] != 'admin') : ?>

    <form action="" method="POST">
        <legend>Tu as un code cadeau ?</legend>
        <div class="form-input">
            <input type="text" id="gift-code" name="gift-code">
            <?php if(isset($code_errors)): ?>
                <p class="error"><?= $code_errors ?></p>
            <?php endif; ?>
        </div>
        <input type="submit" name="code-submit" value="Valider">
    </form>
    <br>

    <div class="frame">
        <legend>Supprimer mon compte</legend>
        <input type="button" value="Supprimer" class="delete">
    </div>
    <br>

    <div class="pop-up-background">
    </div>

    <form class="pop-up" method="POST">
        <p>Êtes-vous sûr de vouloir supprimer votre compte ?</p>
        <p>Vous perdrez l'accès à tous les packs que vous avez achetés !</p>
        <p class="warning"><b>Cette action est irréversible !</b></p>
        <div class="form-input">
            <label for="delete-password">Entrez votre mot de passe</label>
            <input type="password" id="delete-password" name="delete-password">
        </div>
        <input type="submit" name="delete-account" value="Supprimer mon compte">
        <input type="button" value="Annuler" class="cancel">
    </form>

<?php endif ?>

<script src="<?= asset('js/deletePopUp.js') ?>"></script>