<br>
<?php if (!isset($_SESSION['user']['packs']) || !in_array($_GET['id'], $_SESSION['user']['packs'])): ?>
    <div class="command">
        <legend>Résumé de la commande</legend>
        <img class="pack-image" src="<?= asset('images/'.$packSelected->getImage()) ?>" alt="<?= $packSelected->getTitle() ?>" style="margin:0; width: 200px";>
        <p>Prix : <?= $packSelected->getPrice() ?> €</p>
    </div>
<?php endif; ?>

<?php if (!isset($_SESSION['user']['id'])) { ?>
    
    <p>Connectez-vous ou inscrivez-vous pour procéder au paiement<br>
    Vous pourrez accéder aux cours en vous connectant à votre compte</p>

    <?php if (isset($new_user)): ?>
        <p class="success"><?= $new_user ?></p>
    <?php endif; ?>
    
    <!-- Login form -->
    <form action="" method="POST" class="login-form" <?php if ($_SESSION['show_register']) { echo 'style="display:none"'; } ?>>
        <legend>Connexion</legend>
        <div class="form-input">
            <label for="email">Email</label>
            <input type="text" id="email" name="email-login" value="<?= $email_login ?>">
            <?php if (isset($errors['email_login'])) { ?>
                <p class="error"><?= $errors['email_login'] ?></p>
            <?php } ?>
        </div>
        <div class="form-input">
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password-login">
            <?php if (isset($errors['password_login'])) { ?>
                <p class="error"><?= $errors['password_login'] ?></p>
            <?php } ?>
        </div>
        <input type="submit" name="login-submit" value="Se connecter">
        <p>Pas encore inscris ? <a href="#" class="register">S'inscrire</a></p>
        <p><a href="<?=constructUrl('forgot-password')?>">Mot de passe oublié ?</a></p>
    </form>

    <!-- Register form -->
    <form action="" method="POST" class="register-form" <?php if ($_SESSION['show_register']) { echo 'style="display:block"'; } ?>>
        <legend>Inscription</legend>
        <div class="form-input">
            <label for="lastname">Nom</label>
            <input type="text" id="lastname" name="lastname" value="<?= $lastname ?>">
            <?php if (isset($errors['lastname'])) { ?>
                <p class="error"><?= $errors['lastname'] ?></p>
            <?php } ?>
        </div>
        <div class="form-input">
            <label for="firstname">Prénom</label>
            <input type="text" id="firstname" name="firstname" value="<?= $firstname ?>">
            <?php if (isset($errors['firstname'])) { ?>
                <p class="error"><?= $errors['firstname'] ?></p>
            <?php } ?>
        </div>
        <div class="form-input">
            <label for="email">Email</label>
            <input type="email" id="email" name="email" value="<?= $email ?>">
            <?php if (isset($errors['email'])) { ?>
                <p class="error"><?= $errors['email'] ?></p>
            <?php } ?>
        </div>
        <div class="form-input">
            <label for="password">Mot de passe</label>
            <input type="password" id="password" name="password">
            <?php if (isset($errors['password'])) { ?>
                <p class="error"><?= $errors['password'] ?></p>
            <?php } ?>
        </div>
        <div class="form-input">
            <label for="password">Confirmer le mot de passe</label>
            <input type="password" id="password2" name="password2">
            <?php if (isset($errors['password2'])) { ?>
                <p class="error"><?= $errors['password2'] ?></p>
            <?php } ?>
        </div>
        <input type="submit" name="register-submit" value="S'inscrire">
        <p>Déjà inscris ? <a href="#" class="login">Se connecter</a></p>
    </form>

<?php } else { ?>

    <?php if (isset($packAlreadyPurchased) AND $packAlreadyPurchased == true) { ?>

        <p>Vous avez déjà accès à ce contenu</p>
                
    <?php } else { ?>

        <!-- Payment form -->
        <form action="" method="POST" class="payment-form">
            <div class="form-input">
                <label for="card-number">Numéro de la carte</label>
                <input type="text" id="card-number" placeholder="•••• •••• •••• ••••" data-stripe="number">
            </div>
            <div class="form-input">
                <label for="exp-date">Date d'expiration</label>
                <div class="exp-date">
                    <input type="text" placeholder="MM" data-stripe="exp_month">
                    <input type="text" placeholder="YY" data-stripe="exp_year">
                </div>
            </div>
            <div class="form-input">
                <label for="cvc">Code de sécurité</label>
                <input type="text" id="cvc" placeholder="CVC" data-stripe="cvc">
            </div>
            <div class="form-input">
                <label for="card-name">Titulaire de la carte</label>
                <input type="text" id="card-name" placeholder="NOM Prénom">
            </div>
            <input type="submit" name="buy-submit" value="Acheter">
        </form>

    <?php } ?>           

<?php } ?>

<p class="present">Vous souhaitez offrir un pack à un proche ? <a href="<?=constructUrl('present')?>">Cliquez ici</a></p>

<script>

    const registerForm = document.querySelector('.register-form');
    const loginForm = document.querySelector('.login-form');

    document.querySelector('.register').addEventListener('click', () => {
        registerForm.style.display = "block";
        loginForm.style.display = "none";
    })

    document.querySelector('.login').addEventListener('click', () => {
        registerForm.style.display = "none";
        loginForm.style.display = "block";
    })

</script>